# Generated by Django 3.0.8 on 2020-07-08 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witems', to='auctions.Listing')),
                ('luser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
