# Generated by Django 3.0.8 on 2020-07-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200712_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Image',
            field=models.CharField(max_length=300),
        ),
    ]
